### ISSUE TITLE
`from_zenodo` raises excepction

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1279]
For packages loaded from Zenodo the `from_zenodo` function raises an exception `Not supported Zenodo source 'None' or control`.

Here are the steps to reproduce:

```bash
python -m venv .
. bin/activate
pip install frictionless==5.0.0b10
pip install frictionless[zenodo]==5.0.0b10
pip install frictionless[excel]==5.0.0b10
```

```python
from frictionless import Package
p = Package('https://zenodo.org/record/7078768')
p.from_zenodo()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/zenodo/lib/python3.10/site-packages/frictionless/package/package.py", line 493, in from_zenodo
    raise FrictionlessException(
frictionless.exception.FrictionlessException: [error] Not supported Zenodo source 'None' or control 
```

**Comment by shashigharti** [comment]
Thank you for trying this new feature!.

Can you please try as follows and it should work:
```
package = Package("https://zenodo.org/record/7078768")
print(package)
```

OR
This is a class method.
```
package = Package.from_zenodo("https://zenodo.org/record/7078768")
print(package)
```

**Comment by jze** [comment]
The fact that `from_zenodo` is a class method explains the problem.
