### ISSUE TITLE
Publishing a remote data package to CKAN with foreign keys throws error `failed to handle a foreign key for resource "x" as resource "y" does not exist`

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1355]
When trying to publish [this package](https://github.com/transparencia-mg/datapackage-reprex/tree/foreign-key-constraint) to CKAN I get the following error:

```python
from frictionless.portals import CkanControl
from frictionless import Package

package = Package('datapackage.json')

config = CkanControl(baseurl='https://homologa.cge.mg.gov.br', apikey='ec5c0860-9e48-41f3-8850-4a7128b18df8') # not a real key

package.publish(control=config)
# Traceback (most recent call last):
#   File "frictionless/portals/ckan/adapter.py", line 200, in write_resource
#     resource.read_bytes(),
#   File "frictionless/resource/resource.py", line 883, in read_bytes
#     with helpers.ensure_open(self):
#   File "contextlib.py", line 135, in __enter__
#     return next(self.gen)
#   File "frictionless/helpers.py", line 99, in ensure_open
#     thing.open()
#   File "frictionless/resource/resource.py", line 616, in open
#     self.__prepare_lookup()
#   File "frictionless/resource/resource.py", line 722, in __prepare_lookup
#     raise FrictionlessException(errors.ResourceError(note=note))
# frictionless.exception.FrictionlessException: [resource-error] The data resource has an error: failed to handle a foreign key for resource "pib-per-capita" as resource "estados" does not exist 
```

**Comment by fjuniorr** [comment]
The error message is similar to https://github.com/frictionlessdata/framework/issues/1136, but in this case the package is valid:

```python
package.validate()
```

```python
{'valid': True,
 'stats': {'tasks': 2, 'warnings': 0, 'errors': 0, 'seconds': 0.044},
 'warnings': [],
 'errors': [],
 'tasks': [{'valid': True,
            'name': 'estados',
            'type': 'table',
            'place': 'data/estados.csv',
            'labels': ['COD', 'NOME', 'SIGLA'],
            'stats': {'md5': '99167485b6ca41cfa6a97dc8bdf39fa1',
                      'sha256': 'c280dab2e21da93be52aef5a4c934abdd4d70d9981f59372e3f36f4ca8b1ac38',
                      'bytes': 496,
                      'fields': 3,
                      'rows': 27,
                      'warnings': 0,
                      'errors': 0,
                      'seconds': 0.012},
            'warnings': [],
            'errors': []},
           {'valid': True,
            'name': 'pib-per-capita',
            'type': 'table',
            'place': 'data/pib-per-capita.csv',
            'labels': ['COD', 'POP_2013', 'PIB_2013', 'PIB_PER_CAPITA_2013'],
            'stats': {'md5': 'ff296ada55aef23adc4ee4e6b1da6513',
                      'sha256': 'eb51e940137ef67997ce14a4ca9895e9299cc06479e371e005e35e48082c3457',
                      'bytes': 1221,
                      'fields': 4,
                      'rows': 27,
                      'warnings': 0,
                      'errors': 0,
                      'seconds': 0.021},
            'warnings': [],
            'errors': []}]}
```

**Comment by shashigharti** [comment]
Thanks @fjuniorr, we will look into it!.

**Comment by aivuk** [comment]
@roll with the last (https://github.com/frictionlessdata/framework/commit/858bb2d84b33c1f6e22acdd6a9e3b56ba80672ef) framework  version I was able to load the datapackage above and upload to a CKAN instance using the framework. The only problem is that you do need to ran the python code inside the folder with the datapackage.json, data/ and schema/ folders, otherwise the framework fails to load the schema files referenced relative to the datapackage.json folder.

**Comment by roll** [comment]
I tested it with:

```
from frictionless import Package, portals

API_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJwdlN4X20yQlBQTXZXT1V4U1djNGI4cUhsOTF5bUdZSDNJeldFdDJXYXZBIiwiaWF0IjoxNjc3NTgxOTgyfQ.V1uFmLrccZ-35BkShBX0ij2ktHqUnxSCnagAbPIoKI4"
package = Package(
    "https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint/datapackage.json"
)
package.publish(
    control=portals.CkanControl(
        baseurl="http://ckan:5000", apikey=API_TOKEN, organization_name="default"
    )
)
```

It worked for me. Closing for now
