### ISSUE TITLE
frictionless auto-generates header name for missing header but transforms using this name fail

### ISSUE THREAD

**Issue by hjoukl** [frictionlessdata/frictionless-py#1394]
# Overview

Can't use an auto-generated header name to remove this field (column).

# Details
Given a `colors.csv` with a missing 3rd header row name:

```
no,color,
1,red,The color of blood
2,green,The color of hope
3,blue,The color of oceans
```

... frictionless conveniently generates a header field name `field3`:

```
$ python -c 'from frictionless import describe; resource = describe("colors.csv"); print(resource.to_view())'
+----+---------+-----------------------+
| no | color   | field3                |
+====+=========+=======================+
|  1 | 'red'   | 'The color of blood'  |
+----+---------+-----------------------+
|  2 | 'green' | 'The color of hope'   |
+----+---------+-----------------------+
|  3 | 'blue'  | 'The color of oceans' |
+----+---------+-----------------------+
```

However, on can not use it for transformation pipelines:

```
(.venv) 0 $ cat transform_colors.py
#!/usr/bin/env python

from frictionless import Dialect, describe, formats, transform, steps


resource = describe("colors.csv")
print(resource.to_view())

transformed = transform(
    resource,
    steps=[
        steps.field_remove(names=["field3"])
        ]
    )

print(transformed.to_view())

(.venv) 0 $ ./transform_colors.py
+----+---------+-----------------------+
| no | color   | field3                |
+====+=========+=======================+
|  1 | 'red'   | 'The color of blood'  |
+----+---------+-----------------------+
|  2 | 'green' | 'The color of hope'   |
+----+---------+-----------------------+
|  3 | 'blue'  | 'The color of oceans' |
+----+---------+-----------------------+

Traceback (most recent call last):
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/methods/transform.py", line 68, in __iter__
    yield from self.data() if callable(self.data) else self.data
  File ".venv/lib64/python3.8/site-packages/petl/transform/basics.py", line 206, in itercutout
    indicesout = asindices(hdr, spec)
  File ".venv/lib64/python3.8/site-packages/petl/util/base.py", line 299, in asindices
    raise FieldSelectionError(s)
petl.errors.FieldSelectionError: selection is not a field or valid field index: 'field3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./transform_colors.py", line 16, in <module>
    print(transformed.to_view())
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/resource.py", line 998, in to_view
    view = str(getattr(self.to_petl(normalize=True), type)(**options))
  File ".venv/lib64/python3.8/site-packages/petl/util/vis.py", line 104, in __repr__
    table, overflow = _vis_overflow(self.table, self.limit)
  File ".venv/lib64/python3.8/site-packages/petl/util/vis.py", line 528, in _vis_overflow
    table = list(islice(table, 0, limit+2))
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/resource.py", line 1038, in __iter__
    with resource:
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/resource.py", line 171, in __enter__
    self.open()
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/resource.py", line 608, in open
    self.__prepare_parser()
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/resource.py", line 663, in __prepare_parser
    self.__parser.open()
  File ".venv/lib64/python3.8/site-packages/frictionless/system/parser.py", line 95, in open
    self.__cell_stream = self.read_cell_stream()
  File ".venv/lib64/python3.8/site-packages/frictionless/system/parser.py", line 136, in read_cell_stream
    for cells in cell_stream:
  File ".venv/lib64/python3.8/site-packages/frictionless/system/parser.py", line 196, in __next__
    return self.cell_stream.__next__()  # type: ignore
  File ".venv/lib64/python3.8/site-packages/frictionless/formats/inline/parser.py", line 41, in read_cell_stream_create
    item = next(data)
  File ".venv/lib64/python3.8/site-packages/frictionless/resource/methods/transform.py", line 74, in __iter__
    raise FrictionlessException(error) from exception
frictionless.exception.FrictionlessException: [step-error] Step is not valid: "field_remove" raises "selection is not a field or valid field index: 'field3'" 
```

I haven't fully grasped it but it looks like the generated header field name is not used consistently. I.e. somehow the
 `petl` utilities used (for cutting out a field) don't get handed the header info *including* the generated name but only the actual given header names (labels?), as in the original data.

Same for e.g. xlsx data files.

[colors.csv](https://github.com/frictionlessdata/framework/files/10465842/colors.csv)
[colors.xlsx](https://github.com/frictionlessdata/framework/files/10465847/colors.xlsx)

**Comment by shashigharti** [comment]
Thanks @hjoukl for reporting!.

**Comment by shashigharti** [comment]
Specifying field names also doesn't work.

``` python
from frictionless import transform, steps, Detector

detector = Detector(field_names=["field1","field2","field3"])
resource = describe("framework/blank-header.csv", detector=detector)
print(resource.to_view())
transformed = transform(
    resource,
    steps=[
        steps.field_remove(names=["field2"])
    ]
)
print(transformed.to_view())
```

**Comment by hjoukl** [comment]
FWIW such change in `Resource.to_petl` "heals" the transform:

```
$ diff .venv/lib/python3.8/site-packages/frictionless/resource/resource.py.bak .venv/lib/python3.8/site-packages/frictionless/resource/resource.py
1044c1044,1045
<                         yield resource.header.labels
---
>                         #yield resource.header.labels
>                         yield resource.schema.field_names
```

However, I don't have a good understanding of what labels are meant to be in the 1st place.
I.e. how do they differ from field names. So I'm not sure if field names or labels should be used here.

Looks like labels are kept separately in Resource setup from the get-go, see https://github.com/frictionlessdata/framework/blob/7369ddc04ec75c8f674cbdf5618ae376b4f35803/frictionless/resource/resource.py#L613-L616.

Here, labels are first set in `__prepare_labels` and then used in `__prepare_schema`:

https://github.com/frictionlessdata/framework/blob/7369ddc04ec75c8f674cbdf5618ae376b4f35803/frictionless/resource/resource.py#L682-L687

While `detector.detect_schema()` generates field names for empty header fields the labels are not updated accordingly and kept in sync with these.

HTH, Holger

**Comment by roll** [comment]
Thanks @hjoukl,

I'm releasing `frictionless@5.5.9` with the fix.

Regarding the terminology:
- labels (header) -- from actual data
- field_names -- from schema

For invalid data these two might differ
