### ISSUE TITLE
Import `Resource` gives `TypeError: field() got an unexpected keyword argument 'alias'`

### ISSUE THREAD

**Issue by mattlinares** [frictionlessdata/frictionless-py#1447]
I've just installed frictionless with `pip` on my Mac M2 Os Ventura 13.2.1.

The [first exercise](https://framework.frictionlessdata.io/docs/schemes/remote.html) I try leads to this error: 

```
Python 3.9.12 (main, Apr  5 2022, 01:52:34)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from frictionless import Resource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/__init__.py", line 1, in <module>
    from .actions import describe, extract, transform, validate
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/actions/__init__.py", line 1, in <module>
    from .describe import describe
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/actions/describe.py", line 3, in <module>
    from ..resource import Resource
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/resource/__init__.py", line 1, in <module>
    from .resource import Resource
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/resource/resource.py", line 39, in <module>
    class Resource(Metadata):
  File "/Users/technical/opt/miniconda3/lib/python3.9/site-packages/frictionless/resource/resource.py", line 194, in Resource
    _dialect: Union[Dialect, str] = attrs.field(factory=Dialect, alias="dialect")
TypeError: field() got an unexpected keyword argument 'alias'
>>>
```

Any ideas? Thanks!

**Comment by mangecoeur** [comment]
I am experiencing the same problem on Intel Mac with Anaconda Python 3.10

**Comment by mangecoeur** [comment]
Ok so it seems frictionless requires the latest attrs 22.2.0 but the version that was previously installed by conda was 22.1.0 . frictionless needs to specify the higher version of attrs is required. Currently this is "attrs>=21.3.0" but the alias argument was only introduced in version 22.2.0 https://www.attrs.org/en/stable/changelog.html
