### ISSUE TITLE
Exception thrown when attempting to write a Date-time field with timezone to Parquet

### ISSUE THREAD

**Issue by chenweiss** [frictionlessdata/frictionless-py#1488]
# Overview

Version: frictionless 5.10.5

Attempting to write a Resource to a Parquet file fails if the file contains a Date-time field with a timezone.

Example:
```
>>> r = Resource([["a"], ["2025-08-24T15:00:00Z"]])
>>> r.write("test_dt.parquet")
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/util.py", line 427, in get_column_metadata
    pd.Series([pd.to_datetime('now', utc=True)]).dt.tz_localize(stz)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/accessor.py", line 112, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/indexes/accessors.py", line 128, in _delegate_method
    result = method(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/indexes/datetimes.py", line 279, in tz_localize
    arr = self._data.tz_localize(tz, ambiguous, nonexistent)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/arrays/_mixins.py", line 86, in method
    return meth(self, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 1035, in tz_localize
    raise TypeError("Already tz-aware, use tz_convert to convert.")
TypeError: Already tz-aware, use tz_convert to convert.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/frictionless/resource/resource.py", line 926, in write
    parser.write_row_stream(self)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/frictionless/formats/parquet/parser.py", line 46, in write_row_stream
    platform.fastparquet.write(self.resource.normpath, source.to_pandas())
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/writer.py", line 1294, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/writer.py", line 890, in make_metadata
    get_column_metadata(data[column], column, object_dtype=oencoding))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/util.py", line 434, in get_column_metadata
    raise ValueError("Time-zone information could not be serialised: "
ValueError: Time-zone information could not be serialised: tzutc(), please use another
```

Issue cannot be reproduced if the timezone is removed:
```
>>> r = Resource([["a"], ["2025-08-24T15:00:00"]])
>>> r.write("test_dt.parquet")
{'name': 'test_dt',
 'type': 'table',
 'path': 'test_dt.parquet',
 'scheme': 'file',
 'format': 'parquet',
 'mediatype': 'appliction/parquet'}
```

**Comment by shashigharti** [comment]
Thanks @chenweiss for reporting!.
