### ISSUE TITLE
Skipping check "extra-header" in csv file validation

### ISSUE THREAD

**Issue by ilfoxo** [frictionlessdata/frictionless-py#375]
# Overview

I have a CSV file with more columns that I need, I define my schema like this:

```python
sh = {'fields': 
        [{'name': 'Period start time', 'type': 'datetime', 'format': '%m.%d.%Y %H:%M:%S'}, 
        {'name': 'RNC name', 'type': 'string'}, 
        {'name': 'WBTS name', 'type': 'string'}, 
        {'name': 'WBTS ID', 'type': 'integer'}, 
        {'name': 'txTwampMessages (M5126C8)', 'type': 'number'}, 
        {'name': 'minRTT_15Min', 'type': 'number'},
        {'name': 'maxRTT_15Min (M5126C1)', 'type': 'number'},
        {'name': 'lostTwampMessages (M5126C9)', 'type': 'number'},
        {'name': 'avgRTT_15Min (M5126C0)', 'type': 'number'},
        {'name': 'minRTT_15Min (M5126C2)', 'type': 'number'}
        ]
    }

rep = validate([{"source":"data/DATA_TWAMP.csv", "schema": sh}], skip_checks=['extra-header'], row_limit=10, infer_fields=False, order_fields=True)
```

When I try to validate skipping 'extra-header' check, I get the following error:

````
Traceback (most recent call last):
  File "init.py", line 20, in <module>
    b = validate([{"source":"data/DATA_TWAMP.csv", "schema": sh}], skip_checks=['extra-header'], row_limit=10, infer_fields=False, order_fields=True)
  File "/Users/hector/CloudStation/Personal/Development/Python/uploader/ENVUP/lib/python3.7/site-packages/goodtables/validate.py", line 80, in validate
    report = inspector.inspect(source, **options)
  File "/Users/hector/CloudStation/Personal/Development/Python/uploader/ENVUP/lib/python3.7/site-packages/goodtables/inspector.py", line 83, in inspect
    table_warnings, table_report = task.get()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/hector/CloudStation/Personal/Development/Python/uploader/ENVUP/lib/python3.7/site-packages/goodtables/inspector.py", line 224, in __inspect_table
    errors += check_func(header_cells, sample) or []
  File "/Users/hector/CloudStation/Personal/Development/Python/uploader/ENVUP/lib/python3.7/site-packages/goodtables/checks/missing_header.py", line 25, in missing_header
    field_name = cell['field'].name if cell['field'] else ''
KeyError: 'field'

```
---

**Comment by roll** [comment]
Thanks for reporting,

The new version of `gootables` is about to be released and this problem should be fixed there (as the ordering system was re-worked). 

I'll update this issue when it's published

**Comment by roll** [comment]
It has been fixed in [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py). Please try `validate(..., sync_schema=True)`

See more info about the new framework - https://github.com/frictionlessdata/frictionless-py#frictionless-for-python
