### ISSUE TITLE
Importing Plugin class fails

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#559]
# Overview

Importing `Plugin` class fails.

```bash
> python
Python 3.8.1 (default, Dec 31 2019, 12:42:09) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from frictionless import Plugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pdi/projects/validata/frictionless-py/frictionless/__init__.py", line 36, in <module>
    from . import types
  File "/home/pdi/projects/validata/frictionless-py/frictionless/types/__init__.py", line 12, in <module>
    from .string import StringType
  File "/home/pdi/projects/validata/frictionless-py/frictionless/types/string.py", line 2, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'
```

Tested with frictionless-py `v3.37.0`.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @pierredittgen,

There is a new dependency - https://github.com/frictionlessdata/frictionless-py/blob/3a81229676c760787cbd7ad2768b127ccfacf97e/setup.py#L70

It seems like a weird Pip problem. Can you please try re-installing Frictionless?

**Comment by pierredittgen** [comment]
Thx @roll, issue fixed.
