### ISSUE TITLE
Error when describing pdf file?

### ISSUE THREAD

**Issue by BenPortner** [frictionlessdata/frictionless-py#641]
Dear frictionless-py developers,

First off, thank for your continued effort in promoting frictionless data. I, as a researcher, struggle with badly-formated data every day. I hope future generations will not have to go through the same struggles thanks to your work!

# Overview

I receive an error when trying to run `frictionless.decribe('some.pdf')`. The error says I should install `frictionless-pdf` but neither `pip install frictionless-pdf` nor `pip install frictionless[pdf]` solved the problem.

The code:
```python
import frictionless

frictionless.describe('path/to/some.pdf')
```

The error:
```python
Traceback (most recent call last):
  File "C:\Users\user\programs\PyCharm\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\user\programs\miniconda\envs\WPP2\lib\site-packages\frictionless\describe\main.py", line 46, in describe
    return describe(source, **options)
  File "C:\Users\user\programs\miniconda\envs\WPP2\lib\site-packages\frictionless\describe\resource.py", line 129, in describe_resource
    with table as table:
  File "C:\Users\user\programs\miniconda\envs\WPP2\lib\site-packages\frictionless\table.py", line 217, in __enter__
    self.open()
  File "C:\Users\user\programs\miniconda\envs\WPP2\lib\site-packages\frictionless\table.py", line 400, in open
    self.__parser = system.create_parser(self.__resource)
  File "C:\Users\user\programs\miniconda\envs\WPP2\lib\site-packages\frictionless\system.py", line 161, in create_parser
    raise FrictionlessException(errors.FormatError(note=note))
frictionless.exception.FrictionlessException: [format-error] The data source could not be successfully parsed: cannot create parser "pdf". Try installing "frictionless-pdf"
```

The pdf file that causes the error can be downloaded [here](https://population.un.org/wpp/Download/Files/4_Metadata/WPP2019_Data-Sources.pdf).

Thank you in advance for your help.
Ben

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @BenPortner,

Thanks, it's a bug I'm going to fix. Initially, it was created to work only with tabular data so it tries to find a tabular pdf parser. I will change this behavior

**Comment by BenPortner** [comment]
Thanks, @roll. I'm glad to hear it was not just me being clumsy 😄
