### ISSUE TITLE
frictionless 4: Recursion error

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#647]
# Overview

I migrate code from `frictionless 3.48.0` to `frictionless 4.0.a10`. Reading this csv file : [data.csv.txt](https://github.com/frictionlessdata/frictionless-py/files/5910563/data.csv.txt) with frictionless-py 3 works fine but fails with `RecursionError` with frictionless-py 4

Did I miss something during migration?

### frictionless-py 3.* code

```python
import frictionless

source = open("data.csv.txt", "rb").read().decode("iso-8859-1")
source_options = {"format": "csv", "scheme": "text"}
with frictionless.Table(source, **source_options) as table:
    data = list(table.data_stream)
    head = data[0]
    assert "accessibilité" in head, head
```

Runs fine.

### frictionless-py 4.*

```python
import frictionless

source = open("data.csv.txt", "rb").read().decode("iso-8859-1")
source_options = {"format": "csv", "scheme": "text"}
with frictionless.Resource(source, **source_options) as res:
    data = list(res.data_stream)
    head = data[0]
    assert "accessibilité" in head, head
```

Fails :-(

See stacktrace:
```bash
Traceback (most recent call last):
  File "fl_4.py", line 8, in <module>
    with frictionless.Resource(source, **source_options) as res:
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/frictionless/resource.py", line 173, in __init__
    file = system.create_file(source, basepath=basepath)
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/frictionless/system.py", line 125, in create_file
    file = File(source, **options)
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/frictionless/file.py", line 25, in __init__
    self.__detect()
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/frictionless/file.py", line 119, in __detect
    for part in sorted(glob.glob(pattern, **options)):
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/glob.py", line 73, in _iglob
    for dirname in dirs:
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/glob.py", line 73, in _iglob
    for dirname in dirs:
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/glob.py", line 73, in _iglob
    for dirname in dirs:
  [Previous line repeated 985 more times]
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/glob.py", line 42, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/posixpath.py", line 104, in split
    sep = _get_sep(p)
  File "/home/pdi/.pyenv/versions/3.8.1/lib/python3.8/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, I'll fix it

**Comment by roll** [comment]
I checked this out and realized that the root of this problem was the legacy `text` loader. This loader was used mostly for testing purposes and lately created a lot of problems as it was basically data living in the path.

From v4 there will be the `buffer` loader instead (where the source is Python bytes):

```python
def test_buffer_loader_recursion_error_issue_647():
    with open("data/issue647.csv.txt", "rb") as file:
        with Resource(file.read(), format="csv", encoding="iso-8859-1") as resource:
            assert len(resource.read_lists()) == 883 # NOTE resource.read_lists from v4.0.0a11
```

**Comment by roll** [comment]
Also, I would change the code snippet slightly using last API improvements:

```python
from frictionless import Resource

with Resource("tmp/issue647.csv.txt", format="csv", encoding="iso-8859-1") as resource:
    assert "accessibilité" in resource.labels  # or resource.header for normalized labels
```
