### ISSUE TITLE
extract doc errors

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionless-py#682]
Hi @roll here are the code errors I got when going through the extract doc. I double-checked that I was using version Frictionless 4.0.1 & Python 3.8.1:

1. The example starting on line 111 gives me an error. It looks like the schema isn't being inferred so there isn't a `fields` property?
<img width="963" alt="Screen Shot 2021-02-10 at 4 19 48 PM" src="https://user-images.githubusercontent.com/17657625/107582712-8806ba80-6bbf-11eb-8618-4732e9d2fbc7.png">

<img width="1169" alt="Screen Shot 2021-02-10 at 4 12 23 PM" src="https://user-images.githubusercontent.com/17657625/107582668-71606380-6bbf-11eb-9f25-758848814d84.png">

2. Extracting more than 1 data file isn't working in the CLI or in Python. The first issue starts on line 145:
<img width="938" alt="Screen Shot 2021-02-10 at 4 24 35 PM" src="https://user-images.githubusercontent.com/17657625/107583094-13804b80-6bc0-11eb-9352-e3f3abfef978.png">

<img width="1110" alt="Screen Shot 2021-02-10 at 4 24 17 PM" src="https://user-images.githubusercontent.com/17657625/107583137-1da24a00-6bc0-11eb-9fea-e38a720f5bd9.png">

3. And here is the same extracting a package error with Python on line 181: 
<img width="475" alt="Screen Shot 2021-02-10 at 4 25 47 PM" src="https://user-images.githubusercontent.com/17657625/107583292-4de9e880-6bc0-11eb-8f55-d9dc3bd27735.png">

<img width="553" alt="Screen Shot 2021-02-10 at 4 25 40 PM" src="https://user-images.githubusercontent.com/17657625/107583325-55a98d00-6bc0-11eb-8e1c-e85ee2457b86.png">

4. The last error I got was about streaming data on line 243. `data_stream` was the only one that gave me a problem:
<img width="652" alt="Screen Shot 2021-02-10 at 4 30 47 PM" src="https://user-images.githubusercontent.com/17657625/107583411-77a30f80-6bc0-11eb-8e37-c1eefe39b603.png">
<img width="792" alt="Screen Shot 2021-02-10 at 4 30 41 PM" src="https://user-images.githubusercontent.com/17657625/107583453-85f12b80-6bc0-11eb-9988-2fcf4a0e60c5.png">

Let me know if I can provide you with any other information! Thanks!

**Comment by lwinfree** [comment]
Hi @roll I'm still getting the errors about extracting more than one file at once. 
With Python:
```
>>> from frictionless import extract
>>> data = extract('frictionless-py/data/*-3.csv')
>>> from pprint import pprint
>>> for path, rows in data.items():
...   pprint(path)
...   pprint(rows)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'items'
```

And with the CLI:
```
lillywinfree@Lillys-MacBook-Pro Frictionlessdata % frictionless extract frictionless-py/data/*-3.csv
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.8.1/bin/frictionless", line 8, in <module>
    sys.exit(program())
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/frictionless/program/extract.py", line 141, in program_extract
    normdata = {source: data}
TypeError: unhashable type: 'list'
```

**Comment by lwinfree** [comment]
for future users (and @roll): this IS working now! I hadn't updated to version 4.0.2.
