### ISSUE TITLE
Python 3.6 UnicodeDecodeError ascii codec opening package

### ISSUE THREAD

**Issue by karlcz** [frictionlessdata/frictionless-py#763]
# Overview

A user reported a failure using the `frictionless validate path/to/package.json` CLI on Python 3.6.  It seems to me that there is probably a portability issue here between Python minor versions and how ascii vs utf8 encoding is chosen?

```
Traceback (most recent call last):
 File "/home/dc12/work/CFDE/cfde_venv/bin/frictionless", line 5, in <module>
  from frictionless.__main__ import program
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/__init__.py", line 1, in <module>
  from .check import Check
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/check.py", line 1, in <module>
  from .metadata import Metadata
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/metadata.py", line 12, in <module>
  from .helpers import cached_property
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/helpers.py", line 19, in <module>
  from . import config
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/config.py", line 26, in <module>
  SCHEMA_PROFILE = json.loads(read_asset("profiles", "schema", "general.json"))
 File "/home/dc12/work/CFDE/cfde_venv/lib/python3.6/site-packages/frictionless/config.py", line 13, in read_asset
  return io.open(os.path.join(dirname, "assets", *paths)).read().strip()
 File "/opt/python/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
  return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7807: ordinal not in range(128)
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks. I will investigate. Can you please share a data sample?

**Comment by karlcz** [comment]
Sorry, you may want to hold off...  We're still trying to get
sufficient detail from the user as it turns out I haven't been able to
reproduce it on a Python 3.6 test installation either.

**Comment by roll** [comment]
Ok. Cool. Please re-open than if needed

**Comment by yuanzhou** [comment]
We ran into the similar issue with frictionless 4.0.0 on Python 3.9. 
```
File "/usr/src/app/src/./wsgi.py", line 1, in <module>
    from app import app as application
  File "/usr/src/app/src/./app.py", line 19, in <module>
    from routes.validation import validation_blueprint
  File "/usr/src/app/src/./routes/validation/__init__.py", line 8, in <module>
    ingest_validation_tools_upload = import_module('ingest_validation_tools.upload')
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/src/app/src/./routes/validation/ingest_validation_tools/src/ingest_validation_tools/upload.py", line 8, in <module>
    from ingest_validation_tools.validation_utils import (
  File "/usr/src/app/src/./routes/validation/ingest_validation_tools/src/ingest_validation_tools/validation_utils.py", line 11, in <module>
    from ingest_validation_tools.table_validator import (
  File "/usr/src/app/src/./routes/validation/ingest_validation_tools/src/ingest_validation_tools/table_validator.py", line 6, in <module>
    import frictionless
  File "/usr/local/lib/python3.9/site-packages/frictionless/__init__.py", line 1, in <module>
    from .check import Check
  File "/usr/local/lib/python3.9/site-packages/frictionless/check.py", line 1, in <module>
    from .metadata import Metadata
  File "/usr/local/lib/python3.9/site-packages/frictionless/metadata.py", line 12, in <module>
    from .helpers import cached_property
  File "/usr/local/lib/python3.9/site-packages/frictionless/helpers.py", line 18, in <module>
    from . import config
  File "/usr/local/lib/python3.9/site-packages/frictionless/config.py", line 26, in <module>
    SCHEMA_PROFILE = json.loads(read_asset("profiles", "schema", "general.json"))
  File "/usr/local/lib/python3.9/site-packages/frictionless/config.py", line 13, in read_asset
    return io.open(os.path.join(dirname, "assets", *paths)).read().strip()
  File "/usr/lib64/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7807: ordinal not in range(128)
```
Upgrading to frictionless 5.5.5 addressed the issue. Is this a known bug of the older release and had been fixed in the newer release?

**Comment by roll** [comment]
I think the detection precision improved in v5 so there is no error anymore. Anyway unless the encoding is provided by the user the framework can't guarantee to guess it 100% correct

**Comment by yuanzhou** [comment]
> I think the detection precision improved in v5 so there is no error anymore. Anyway unless the encoding is provided by the user the framework can't guarantee to guess it 100% correct

Thanks for clarifying!
