### ISSUE TITLE
frictionless.validate fails on a data package with inline data

### ISSUE THREAD

**Issue by olejandro** [frictionlessdata/frictionless-py#921]
# Overview

The following code fails on a local copy of https://github.com/MaREI-EPMG/ireland-carbon-budget-scenarios-2021/

```
import frictionless as fs
package = fs.Package("datapackage.json")
fs.validate(package)
```

It results in:

```
Traceback (most recent call last):

  File "C:\Program Files\Python39\lib\site-packages\IPython\core\formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 607, in inner
    p.pretty(obj[key])

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 555, in inner
    p.pretty(x)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 607, in inner
    p.pretty(obj[key])

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 607, in inner
    p.pretty(obj[key])

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Program Files\Python39\lib\site-packages\IPython\lib\pretty.py", line 600, in inner
    keys = obj.keys()

TypeError: 'NoneType' object is not callable
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks for reporting!
