### ISSUE TITLE
frictionless.describe fails on a data package with inline data

### ISSUE THREAD

**Issue by olejandro** [frictionlessdata/frictionless-py#931]
# Overview

The following code fails on a local copy of https://github.com/MaREI-EPMG/ireland-carbon-budget-scenarios-2021/

```
import frictionless as fs
package = fs.Package("datapackage.json")
fs.describe(package)
```
It results in:
```
Traceback (most recent call last):

  File "<ipython-input-11-73ea3d070c9e>", line 1, in <module>
    fs.describe(package)

  File "C:\Program Files\Python39\lib\site-packages\frictionless\describe\main.py", line 30, in describe
    return describe(source, **options)

  File "C:\Program Files\Python39\lib\site-packages\frictionless\describe\resource.py", line 22, in describe_resource
    resource.infer(stats=stats)

  File "C:\Program Files\Python39\lib\site-packages\frictionless\resource.py", line 724, in infer
    with self:

  File "C:\Program Files\Python39\lib\site-packages\frictionless\resource.py", line 288, in __enter__
    self.open()

  File "C:\Program Files\Python39\lib\site-packages\frictionless\resource.py", line 761, in open
    raise FrictionlessException(error)

FrictionlessException: [resource-error] The data resource has an error: "{'name': 'ireland-carbon-budget-scenarios-2021', 'title': "Carbon Budget Scenarios for Ireland's Energy System, 2021-50", 'licenses': [{'name': 'CC-BY-4.0', 'path': 'https://creativecommons.org/licenses/by/4.0/', 'title': 'Creative Commons Attribution 4.0 International License', 'attribution': '© University College Cork'}], 'resources': [{'path': 'data/agr_fec.csv', 'name': 'agr_fec', 'profile': 'tabular-data-resource', 'scheme': 'file', 'format': 'csv', 'hashing': 'md5', 'encoding': 'utf-8', 'schema': {'fields': [{'name': 'scenarioName', 'type': 'string'},

...

{'name': 'PWR-MSW', 'title': 'Municipal Waste'}, {'name': 'R-SW_Det_LPG_N1', 'title': 'LPG SW'}]}], 'profile': 'tabular-data-resource', 'scheme': '', 'format': 'inline', 'hashing': 'md5', 'stats': {'hash': '', 'bytes': 0, 'fields': 0, 'rows': 0}} is not valid under any of the given schemas" at "" in metadata and at "oneOf" in profile
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @olejandro,

The describe command can describe a path or a set of paths (directory). If you want to extend a package's metadata you need to run `package.infer()`

**Comment by roll** [comment]
I hope it hepled

**Comment by olejandro** [comment]
Thanx @roll
yes, it is definitely very helpful! I can see that it is explained quite well what's going on here https://framework.frictionlessdata.io/docs/guides/describing-data/#inferring-metadata
